---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "README-"
)
```

# tidyttest

The goal of tidyttest is to make a t-test function that:

- Can be used as part of a "pipeline"
- Is easy to use programattically (i.e., as part of a function from the `apply()` and `purrr::map()` families)

## Installation

You can install tidyttest from github with:

```{r gh-installation, eval = FALSE, message = F}
# install.packages("devtools")
devtools::install_github("jrosen48/tidyttest")
```

## Example

This is a basic example which shows you how to use the `t_test()` function:

```{r example}
library(dplyr)
library(tidyttest)

storms %>% 
    filter(status %in% c("tropical depression", "tropical storm")) %>% 
    mutate(category = as.integer(category)) %>% 
    t_test(category, status)
```

It outputs a `data.frame`:

```{r}
t_test_df <- t_test(storms, category, status)
t_test_df
```
